All option is now working and now retaining git history

diff --git a/cloudup/cloudup b/cloudup/cloudup
--- a/cloudup/cloudup
+++ b/cloudup/cloudup
@@ -107,7 +107,7 @@ backupRepo()
   originalRepoName=$repoName
   repoName=$(echo $repoName | tr '[:upper:]' '[:lower:]')
   timestamp=$(echo $timestamp | tr '[:upper:]' '[:lower:]')
-  git remote add origin https://$bbUsername:$password@bitbucket.org/$bbUsername/$repoName$timestamp.git > /dev/null || return 1
+  git remote set-url origin https://$bbUsername:$password@bitbucket.org/$bbUsername/$repoName$timestamp.git > /dev/null || return 1
   echo "Uploading $originalRepoName to bitbucket"
   git push -q --progress origin --all > /dev/null || return 1
   echo "Uploading the tags for $originalRepoName"
@@ -119,13 +119,13 @@ backupRepo()
 copyRepository()
 {
   timestamp=$(date | tr " " _ | tr : _  )
-  cp -r $1 ~/temp || { rm -rf ~/temp; return 1;  }
+  cp -r ~/temp/github/$repoName ~/temp || { rm -rf ~/temp; return 1;  }
   cd ~/temp || { rm -rf ~/temp; return 1;  }
   #repoName=$(ls ~/temp)
   cd $repoName || { rm -rf ~/temp; return 1;  }
-  rm -rf .git && git init > /dev/null
-  git add -A . > /dev/null
-  git commit -m "Initial commit" > /dev/null
+  #rm -rf .git && git init > /dev/null
+  # git add -A . > /dev/null
+  # git commit -m "Initial commit" > /dev/null
 }
 
 getGitHubRepoInfo()
@@ -143,11 +143,11 @@ getGitHubUserInfo()
 cloneGitHubRepo()
 {
   mkdir ~/temp
-  cd 
+  cd
   mkdir ~/temp/github
   cd ~/temp/github
   echo "Cloning $repoName"
-  git clone -q --progress https://github.com/$ghUsername/$repoName
+  git clone -q --progress https://github.com/$ghUsername/$repoName || return 1
   echo "Successfully cloned $repoName"
 }
 
@@ -155,9 +155,9 @@ getGithubRepoNames()
 {
   response=$(httpGet "https://api.github.com/users/$ghUsername/repos?sort=updated&per_page=100"  | grep -Eo '"name": "[ a-Z .  \/ \\ 0-9 -- _ ]*' | sed  s/'"name": "'/""/g)
   for repo in $response
-do
+  do
     repoNames+=("$repo")
-done
+  done
 }
 
 usage()
@@ -182,7 +182,7 @@ while getopts "pauvh" opt; do
     ;;
     p)
       private="1"
-      echo "Feature not added yet, for now all backups must be public (can be manually set to private through bitbucket)" >&2
+      echo "Feature not added yet, for now all backups must be public (can be manually set to private through bitbucket after backup)" >&2
       exit 0
     ;;
     h)
@@ -191,8 +191,6 @@ while getopts "pauvh" opt; do
     ;;
     a)
       all="1"
-      #echo "Feature not added yet, for now backup repositories individually" >&2
-      #exit 0
     ;;
     v)
       echo "Version $currentVersion"
@@ -226,17 +224,21 @@ elif [ $# -ge 1 ];then
   if [[ $private != "1" ]];then
     for i in "$@"; do
       repoName=$i
+      echo "Starting to backup $repoName"
       cloneGitHubRepo || exit 1
-      copyRepository ~/temp/github/$repoName || { echo "Error: couldnt copy $repoName to ~/temp/$originalRepoName"; exit 1; }
+      copyRepository || { echo "Error: couldnt copy $repoName to ~/temp/$originalRepoName"; exit 1; }
       backupRepo  || { echo "Error: couldnt backup $originalRepoName to bitbucket"; exit 1; }
+      echo
     done
     exit 0
   else
     for i in "${@:2}"; do
       repoName=$i
+      echo "Starting to backup $repoName"
       cloneGitHubRepo || exit 1
-      copyRepository ~/temp/github/$repoName || { echo "Error: couldnt copy $repoName to ~/temp/$repoName"; exit 1; }
+      copyRepository  || { echo "Error: couldnt copy $repoName to ~/temp/$repoName"; exit 1; }
       backupRepo  || { echo "Error: couldnt backup $originalRepoName to bitbucket"; exit 1; }
+      echo
     done
     exit 0
   fi
@@ -260,10 +262,13 @@ else
   for repo in "${repoNames[@]}"
   do
     repoName=$repo
+    echo "Starting to backup $repoName"
     cloneGitHubRepo || exit 1
     copyRepository ~/temp/gitub/$repoName  || { echo "Error: couldnt copy $repoName to ~/temp/$repoName"; exit 1; }
     backupRepo  || { echo "Error: couldnt backup $repoName to bitbucket"; exit 1; }
+    echo
   done
+  echo "Successfully backed up all repositories"
   exit 0
 
 fi
