Stylistic changes to siteciphers

diff --git a/siteciphers/siteciphers b/siteciphers/siteciphers
--- a/siteciphers/siteciphers
+++ b/siteciphers/siteciphers
@@ -5,7 +5,7 @@ currentVersion="1.15.2"
 
 checkOpenSSL()
 {
-  if  ! command -v openssl &>/dev/null ;then
+  if  ! command -v openssl &>/dev/null; then
     echo "Error: to use this tool openssl must be installed" >&2
     return 1
   else
@@ -15,25 +15,25 @@ checkOpenSSL()
 
 getConfiguredClient()
 {
-    if  command -v curl &>/dev/null ; then
-      configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
-      configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
-      configuredClient="fetch"
-    else
-      echo "Error: This tool reqires either curl, wget, or fetch to be installed."
-      return 1
-    fi
+  if  command -v curl &>/dev/null; then
+    configuredClient="curl"
+  elif command -v wget &>/dev/null; then
+    configuredClient="wget"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
+  else
+    echo "Error: This tool reqires either curl, wget, or fetch to be installed."
+    return 1
+  fi
 }
 
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
   case "$configuredClient" in
-    curl) curl -A curl -s "$@";;
-    wget) wget -qO- "$@";;
-    fetch) fetch -o "...";;
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    fetch) fetch -o "..." ;;
   esac
 }
 
@@ -47,10 +47,10 @@ update()
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]];then
+  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]];then
+  elif [[ $latestVersion == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
@@ -58,16 +58,16 @@ update()
       echo "Version $latestVersion available"
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
-      if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
-        cd  ~ || { echo 'Update Failed' ; exit 1 ; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName  ||  { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+      if [[ "$answer" == [Yy] ]]; then
+        cd  ~ || { echo 'Update Failed'; exit 1; }
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
         git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version" ; exit 1; }
-        cd $repositoryName ||  { echo 'Update Failed' ; exit 1 ;}
+        cd $repositoryName || { echo 'Update Failed'; exit 1; }
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName ||  { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
@@ -75,21 +75,22 @@ update()
       echo "$repositoryName is already the latest version"
     fi
   fi
-
 }
 
 usage()
 {
-  echo "Siteciphers"
-  echo "Description: Checks the available ciphers for the SSL of an https site."
-  echo "Usage: siteciphers [flag] or siteciphers [optionalDFlag] [website]"
-  echo "  -u Update Bash-Snippet Tools"
-  echo "  -h Show the help"
-  echo "  -v Get the tool version"
-  echo "  -d Set the delay between requests sent to the site (default is 1 sec)"
-  echo "Examples:"
-  echo "  siteciphers github.com"
-  echo "  siteciphers -d 0.5 github.com"
+  cat <<EOF
+Siteciphers
+Description: Checks the available ciphers for the SSL of an https site.
+Usage: siteciphers [flag] or siteciphers [optionalDFlag] [website]
+  -u  Update Bash-Snippet Tools
+  -h  Show the help
+  -v  Get the tool version
+  -d  Set the delay between requests sent to the site (default is 1 sec)
+Examples:
+  siteciphers github.com
+  siteciphers -d 0.5 github.com
+EOF
 }
 
 checkInternet()
@@ -101,16 +102,15 @@ checkCiphers()
 {
   ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g') # grab all ciphers
   SERVER=$1:443 # setup the connection server
-  for cipher in ${ciphers[*]} # for all possible ciphers
-  do
+  for cipher in ${ciphers[*]}; do # for all possible ciphers
     result=$(echo | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
-    if [[ "$result" =~ ":error:" ]] ; then
+    if [[ "$result" =~ ":error:" ]]; then
       if [[ -z $2 ]]; then
         error=$(echo -n $result | cut -d':' -f6)
         echo "$cipher - NO ($error)"
       fi
     else
-      if [[ "$result" =~ "Cipher is $cipher" || "$result" =~ "Cipher    :" ]] ; then
+      if [[ "$result" =~ "Cipher is $cipher" || "$result" =~ "Cipher    :" ]]; then
         echo "$cipher - YES"
       else
         if [[ -z $2 ]]; then
@@ -122,54 +122,48 @@ checkCiphers()
   done
 }
 
-
-
-
 checkOpenSSL || exit 1
 getConfiguredClient || exit 1
 checkInternet || exit 1
 
-
 if [[ $# == "0" ]]; then
   usage
   exit 1
-elif [[ $1 == "update" ]];then
+elif [[ $1 == "update" ]]; then
   update
   exit 0
-elif [[ $1 == "help" ]];then
+elif [[ $1 == "help" ]]; then
   usage
   exit 0
 fi
 
 while getopts "huvd:" opt; do ## alows for using options in bash
-  case $opt in
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-    ;;
-    d) #set the delay with the -d option
-      DELAY=$OPTARG
-      dFlag="1"
-    ;;
-    u)
-
-      update
-      exit 0
-    ;;
-    h)
-      usage
-      exit 0
-    ;;
-    v)
-      echo "Version $currentVersion"
-      exit 0
-    ;;
-    :) ## will run when no arguments are provided to to e or d options
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-    ;;
+  case "$opt" in
+    \?) echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    d)  #set the delay with the -d option
+        DELAY=$OPTARG
+        dFlag="1"
+        ;;
+    u)  update
+        exit 0
+        ;;
+    h)  usage
+        exit 0
+        ;;
+    v)  echo "Version $currentVersion"
+        exit 0
+        ;;
+    :)  ## will run when no arguments are provided to to d options
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
   esac
 done
 
-if [[ $dFlag == "1" ]];then checkCiphers $3 || exit 1; # if dflag is present input will look like siteciphers -d 0.5 github.com making the website the third arg
-else  checkCiphers $1 || exit 1; fi
+if [[ $dFlag == "1" ]]; then
+  checkCiphers $3 || exit 1 # if dflag is present input will look like siteciphers -d 0.5 github.com making the website the third arg
+else
+  checkCiphers $1 || exit 1
+fi
