Adding python and json functions to skeleton

diff --git a/skeleton b/skeleton
--- a/skeleton
+++ b/skeleton
@@ -20,6 +20,49 @@ getConfiguredClient()
   fi
 }
 
+# The python and JSON functions can be deleted if the script does not need them
+
+## This function determines which version of python is installed on the machine
+getConfiguredPython()
+{
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
+    configuredPython="python2"
+  elif command -v python &>/dev/null; then
+    configuredPython="python"
+  else
+    echo "Error: This tool requires python to be installed."
+    return 1
+  fi
+}
+
+## Don't alter the python call if it's coming from a Mac
+if [[ $(uname) != "Darwin" ]]; then
+  python()
+  {
+    case "$configuredPython" in
+      python3) python3 "$@" ;;
+      python2) python2 "$@" ;;
+      python)  python "$@" ;;
+    esac
+  }
+fi
+
+## Grabs an element from a a json string and then echoes it to stdout
+## $1 = the JSON string
+## $n+1 = the elements to be indexed
+AccessJsonElement() {
+  json="$1"
+  shift
+  accessor=""
+  for element in "$@"; do
+      accessor="${accessor}['$element']"
+  done
+  echo "$json" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)${accessor})"
+  return "$?"
+}
+
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
@@ -134,3 +177,4 @@ fi
 ## The rest of the conditions and code would go here
 ## Make sure to use checkInternet at least once before any time httpGet will be called.
 ## Make sure to call getConfiguredClient at least once before ever calling checkInternet.
+## Make sure to call getConfiguredPython at least once before trying to pipeout to python directly or using AccessJsonElement
