Adding python3 support

diff --git a/lyrics/lyrics b/lyrics/lyrics
--- a/lyrics/lyrics
+++ b/lyrics/lyrics
@@ -25,12 +25,14 @@ getConfiguredClient()
 
 getConfiguredPython()
 {
-  if  command -v python2 &>/dev/null ; then
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
     configuredPython="python2"
-  elif command -v python &>/dev/null ; then
+  elif command -v python &>/dev/null; then
     configuredPython="python"
   else
-    echo "Error: This tool requires python 2 to be installed."
+    echo "Error: This tool requires python to be installed."
     return 1
   fi
 }
@@ -39,11 +41,27 @@ if [[ $(uname) != "Darwin" ]]; then
   python()
   {
     case "$configuredPython" in
-      python2) python2 "$@";;
-      python) python "$@";;
+      python3) python3 "$@" ;;
+      python2) python2 "$@" ;;
+      python)  python "$@" ;;
     esac
   }
 fi
+
+## Grabs an element from a a json string and then echoes it to stdout
+## $1 = the JSON string
+## $n+1 = the elements to be indexed
+AccessJsonElement() {
+  json="$1"
+  shift
+  accessor=""
+  for element in "$@"; do
+      accessor="${accessor}['$element']"
+  done
+  echo "$json" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)${accessor})" 2> /dev/null
+  return "$?"
+}
+
 
 
 ## Allows to call the users configured client without if statements everywhere
@@ -107,7 +125,7 @@ getLyrics()
   encodedArtist=$(echo $1 | sed s/" "/%20/g | sed s/"&"/%26/g | sed s/,/%2C/g | sed s/-/%2D/g)
   encodedSong=$(echo $2 | sed s/" "/%20/g | sed s/"&"/%26/g | sed s/,/%2C/g | sed s/-/%2D/g)
   response=$(httpGet "https://api.lyrics.ovh/v1/$encodedArtist/$encodedSong")
-  lyrics=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['lyrics']" 2> /dev/null)
+  lyrics="$(AccessJsonElement $response "lyrics" 2> /dev/null)"
   if [[ $lyrics == "" ]];then { echo "Error: no lyrics found!"; return 1; }; fi
 }
 
diff --git a/movies/movies b/movies/movies
--- a/movies/movies
+++ b/movies/movies
@@ -36,12 +36,14 @@ httpGet()
 
 getConfiguredPython()
 {
-  if  command -v python2 &>/dev/null ; then
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
     configuredPython="python2"
-  elif command -v python &>/dev/null ; then
+  elif command -v python &>/dev/null; then
     configuredPython="python"
   else
-    echo "Error: This tool requires python 2 to be installed."
+    echo "Error: This tool requires python to be installed."
     return 1
   fi
 }
@@ -50,11 +52,26 @@ if [[ $(uname) != "Darwin" ]]; then
   python()
   {
     case "$configuredPython" in
-      python2) python2 "$@";;
-      python) python "$@";;
+      python3) python3 "$@" ;;
+      python2) python2 "$@" ;;
+      python)  python "$@" ;;
     esac
   }
 fi
+
+## Grabs an element from a a json string and then echoes it to stdout
+## $1 = the JSON string
+## $n+1 = the elements to be indexed
+AccessJsonElement() {
+  json="$1"
+  shift
+  accessor=""
+  for element in "$@"; do
+      accessor="${accessor}['$element']"
+  done
+  echo "$json" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)${accessor})" 2> /dev/null
+  return "$?"
+}
 
 checkInternet()
 {
@@ -72,22 +89,22 @@ getMovieInfo()
   checkResponse=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Response']" 2> /dev/null)
   if [[ $checkResponse == "False" ]]; then { echo "No movie found" ; return 1 ;} fi ## check to see if the movie was found
   # The rest of the code is just extrapolating the data with python from the JSON response
-  title=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Title']" 2> /dev/null)
-  year=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Year']" 2> /dev/null)
-  runtime=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Runtime']" 2> /dev/null)
-  imdbScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][0]['Value']" 2> /dev/null)
-  tomatoScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][1]['Value']" 2> /dev/null)
-  rated=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Rated']" 2> /dev/null)
-  genre=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Genre']" 2> /dev/null)
-  director=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Director']" 2> /dev/null)
-  actors=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Actors']" 2> /dev/null)
-  plot=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Plot']" 2> /dev/null)
+  title="$(AccessJsonElement "$movieInfo" "Title")"
+  year="$(AccessJsonElement "$movieInfo" "Year")"
+  runtime="$(AccessJsonElement "$movieInfo" "Runtime")"
+  imdbScore=$(echo $movieInfo | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Ratings'][0]['Value'])" 2> /dev/null)
+  tomatoScore=$(echo $movieInfo | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Ratings'][1]['Value'])" 2> /dev/null)
+  rated="$(AccessJsonElement "$movieInfo" "Rated")"
+  genre="$(AccessJsonElement "$movieInfo" "Genre")"
+  director="$(AccessJsonElement "$movieInfo" "Director")"
+  actors="$(AccessJsonElement "$movieInfo" "Actors")"
+  plot="$(AccessJsonElement "$movieInfo" "Plot")"
   
   if $detail; then
-    awards=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Awards']" 2> /dev/null)
-    boxOffice=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['BoxOffice']" 2> /dev/null)
-    metacriticScore=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Ratings'][2]['Value']" 2> /dev/null)
-    production=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Production']" 2> /dev/null)
+    awards="$(AccessJsonElement "$movieInfo" "Awards")"
+    boxOffice="$(AccessJsonElement "$movieInfo" "BoxOffice")"
+    metacriticScore=$(echo $movieInfo | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Ratings'][2]['Value'])" 2> /dev/null)
+    production="$(AccessJsonElement "$movieInfo" "Production")"
   fi
 }
 
diff --git a/pwned/pwned b/pwned/pwned
--- a/pwned/pwned
+++ b/pwned/pwned
@@ -35,12 +35,14 @@ httpGet()
 
 getConfiguredPython()
 {
-  if  command -v python2 &>/dev/null; then
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
     configuredPython="python2"
   elif command -v python &>/dev/null; then
     configuredPython="python"
   else
-    echo "Error: This tool requires python 2 to be installed."
+    echo "Error: This tool requires python to be installed."
     return 1
   fi
 }
@@ -66,10 +68,10 @@ getPwned()
 {
 	info=$(httpGet  "https://haveibeenpwned.com/api/v2/breachedaccount/$1") > /dev/null #grab the JSON response
   export PYTHONIOENCODING=utf8 #necessary for python in some cases
-  echo $info | python -c "import sys, json; print json.load(sys.stdin)[0]['Title']" > /dev/null 2>&1 || { echo "Looks like you have not been breached"; exit 1; } #
+  echo $info | python -c "from __future__ import print_function; import sys, json; print(sys.stdin)[0]['Title'])" > /dev/null 2>&1 || { echo "Looks like you have not been breached"; exit 1; } #
   # The rest of the code is just extrapolating the data with python from the JSON response
   echo $info > .pwned.json
-  title=$(python -c "import sys,json;print('\n'.join([u['Title']for u in json.load(open(sys.argv[1]))]))" ".pwned.json")
+  title=$(python -c "from __future__ import print_function; import sys, json; print('\n'.join([u['Title']for u in json.load(open(sys.argv[1]))]))" ".pwned.json")
   rm -f .pwned.json
   unset info # done with the JSON response not needed anymore
 }
diff --git a/qrify/qrify b/qrify/qrify
--- a/qrify/qrify
+++ b/qrify/qrify
@@ -34,6 +34,31 @@ httpGet()
   esac
 }
 
+getConfiguredPython()
+{
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
+    configuredPython="python2"
+  elif command -v python &>/dev/null; then
+    configuredPython="python"
+  else
+    echo "Error: This tool requires python to be installed."
+    return 1
+  fi
+}
+
+if [[ $(uname) != "Darwin" ]]; then
+  python()
+  {
+    case "$configuredPython" in
+      python3) python3 "$@" ;;
+      python2) python2 "$@" ;;
+      python)  python "$@" ;;
+    esac
+  }
+fi
+
 update()
 {
   # Author: Alexander Epstein https://github.com/alexanderepstein
@@ -114,7 +139,6 @@ makeMultiLineQr()
 # Function to get the json response from POST request
 decodeQR() {
   local qrFile="$1"
-  
   if ! echo "$fileName" | grep -E -q ".*\.png$|.*\.PNG$|.*\.gif$|.*\.jpg$|.*\.jpeg$|.*\.GIF$|.*\.JPG$|.*\.JPEG$"
   then
     exit 1
@@ -130,11 +154,11 @@ decodeQR() {
     fetch) echo "Error:-Not supported with wget" >&2 && exit 1;;
   esac
 
-  error=$(echo "$JSONresponse" | python -c 'import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["error"]')
+  error="$(echo "$JSONresponse" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)[0]['symbol'][0]['error'])")"
   
-  if [ "$error" = "None" ]
+  if [[ "$error" == "None" ]]
   then
-    data=$(echo "$JSONresponse" | python -c 'import sys, json; print json.load(sys.stdin)[0]["symbol"][0]["data"]')
+    data="$(echo "$JSONresponse" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)[0]['symbol'][0]['data'])")"
   else
     echo "Error:-$error" >&2 && exit 1
   fi
@@ -202,31 +226,30 @@ elif [[ $# == "1" ]];then
     update || exit 1
     exit 0
   else
-		checkInternet || exit 1
+    getConfiguredPython || exit 1
+	checkInternet || exit 1
     input=$(printf '%s ' "$@")
     makeqr || exit 1
     exit 0
   fi
 else
+  getConfiguredPython || exit 1
+  checkInternet || exit 1
   if [[ $fileoutput == "1" ]]
 	then
-		checkInternet || exit 1
 		input=$(printf '%s ' "${@:3}") # first arg is -f, second is the file name, third onwards is the rest of the argument
 		# will have to be changed when implementing multiline QR code
 		makeQRFile || exit 1
 		exit 0
   elif [[ $decode == "1" ]]
   then
-    checkInternet || exit 1
     ( decodeQR "$fileName" && echo "$data" ) || exit 1
     exit 0
   elif [[ $multiline == "0" ]]; then
-		checkInternet || exit 1
     input=$(printf '%s ' "$@")
     makeqr || exit 1
     exit 0
   else
-    checkInternet || exit 1
     input=$(printf '%s ' "${@:2}")
     makeMultiLineQr || exit 1 ## if multiline that means a flag existed so start from the second argument
     exit 0
diff --git a/taste/taste b/taste/taste
--- a/taste/taste
+++ b/taste/taste
@@ -39,12 +39,14 @@ httpGet()
 
 getConfiguredPython()
 {
-  if  command -v python2 &>/dev/null; then
+  if command -v python3 &>/dev/null; then
+    configuredPython="python3"
+  elif  command -v python2 &>/dev/null; then
     configuredPython="python2"
   elif command -v python &>/dev/null; then
     configuredPython="python"
   else
-    echo "Error: This tool requires python 2 to be installed."
+    echo "Error: This tool requires python to be installed."
     return 1
   fi
 }
@@ -53,11 +55,26 @@ if [[ $(uname) != "Darwin" ]]; then
   python()
   {
     case "$configuredPython" in
+      python3) python3 "$@" ;;
       python2) python2 "$@" ;;
       python)  python "$@" ;;
     esac
   }
 fi
+
+## Grabs an element from a a json string and then echoes it to stdout
+## $1 = the JSON string
+## $n+1 = the elements to be indexed
+AccessJsonElement() {
+  json="$1"
+  shift
+  accessor=""
+  for element in "$@"; do
+      accessor="${accessor}['$element']"
+  done
+  echo "$json" | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)${accessor})"
+  return "$?"
+}
 
 checkInternet()
 {
@@ -115,17 +132,17 @@ getSimilar()
   media=$( echo "$@" | tr " " + )
   response=$(httpGet "https://tastedive.com/api/similar?q=$media&k=$apiKey&info=$info")
   ## Extrapolate the information by parsing the JSON
-  nameOne=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][0]['Name']" 2>  /dev/null || { echo "Error: Did you search a valid item?"; return 1; } )
-  typeOne=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][0]['Type']" 2>  /dev/null)
-  nameTwo=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][1]['Name']" 2>  /dev/null)
-  typeTwo=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][1]['Type']" 2>  /dev/null)
-  nameThree=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][2]['Name']" 2>  /dev/null)
-  typeThree=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][2]['Type']" 2>  /dev/null)
+  nameOne=$(echo $response |python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][0]['Name'])" 2>  /dev/null || { echo "Error: Did you search a valid item?"; return 1; } )
+  typeOne=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][0]['Type'])" 2>  /dev/null)
+  nameTwo=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][1]['Name'])" 2>  /dev/null)
+  typeTwo=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][1]['Type'])" 2>  /dev/null)
+  nameThree=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][2]['Name'])" 2>  /dev/null)
+  typeThree=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][2]['Type'])" 2>  /dev/null)
   if [[ $info == "1" ]];then ## if we want more detailed info we have to grab a few more fields
-    wikiOne=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][0]['wTeaser']" 2>  /dev/null)
-    wikiTwo=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][1]['wTeaser']" 2>  /dev/null)
-    wikiThree=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][2]['wTeaser']" 2>  /dev/null)
-    youtube=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Results'][0]['yUrl']" 2>  /dev/null)
+    wikiOne=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][0]['wTeaser'])" 2>  /dev/null)
+    wikiTwo=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][1]['wTeaser'])" 2>  /dev/null)
+    wikiThree=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][2]['wTeaser'])" 2>  /dev/null)
+    youtube=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Results'][0]['yUrl'])" 2>  /dev/null)
   fi
 }
 
@@ -135,11 +152,11 @@ getInfo()
   export PYTHONIOENCODING=utf8 #necessary for python in some cases
   media=$( echo "$@" | tr " " + )
   response=$(httpGet "https://tastedive.com/api/similar?q=$media&k=$apiKey&info=$info")
-  name=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Info'][0]['Name']")
-  type=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Info'][0]['Type']")
+  name=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Info'][0]['Name'])")
+  type=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Info'][0]['Type'])")
   if [[ $info == "1" ]]; then
-    wiki=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Info'][0]['wTeaser']")
-    youtube=$(echo $response | python -c "import sys, json; print json.load(sys.stdin)['Similar']['Info'][0]['yUrl']")
+    wiki=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Info'][0]['wTeaser'])")
+    youtube=$(echo $response | python -c "from __future__ import print_function; import sys, json; print(json.load(sys.stdin)['Similar']['Info'][0]['yUrl'])")
   else
     wiki="None"
     youtube="None"
