ytview update #2: mdfind & graceful exit
(1) mdfind stuff now in the else statement
(2) added integer checks for $titlenumber + exit 0

diff --git a/ytview/ytview b/ytview/ytview
--- a/ytview/ytview
+++ b/ytview/ytview
@@ -110,10 +110,24 @@ getConfiguredPlayer()
       player="/Applications/mpv.app/Contents/MacOS/mpv"
     elif [[ -f $HOME/Applications/mpv.app/Contents/MacOS/mpv ]]; then
       player="$HOME/Applications/mpv.app/Contents/MacOS/mpv"
-    else
-      echo "Error: no supported video player installed (vlc or mpv)" >&2
-      return 1
-    fi
+	else
+	  if [[ $(mdutil -s / | grep "Indexing enabled." 2>/dev/null) != "" ]]; then
+	    vlc_md=$(mdfind kMDItemCFBundleIdentifier = "org.videolan.vlc" 2>/dev/null)
+	    if [[ $vlc_md != "" ]]; then
+	      player="$vlc_md/Contents/MacOS/VLC"
+	    else
+	      mpv_md=$(mdfind kMDItemCFBundleIdentifier = "io.mpv" 2>/dev/null)
+	      if [[ $mpv_md != "" ]]; then
+	        player="$mpv_md/Contents/MacOS/mpv"
+	      else
+	        echo "Error: no supported video player installed (VLC or mpv)" >&2
+	        return 1
+	      fi
+	    fi
+	  else
+	    echo "Error: no supported video player installed (VLC or mpv)" >&2
+	    return 1
+	  fi
   fi
 }
 
@@ -130,6 +144,10 @@ channelview()
   head -n 20 $HOME/.cache/ytview/channels/$channel/titles.txt || return 1
   # Prompt the user for video number
   read -p "Choose a video: " titlenumber
+  if [[ -n ${titlenumber//[0-9]/} ]]; then
+    echo "Canceled." >&2
+    exit 0
+  fi
 
   # Play the video with your player
   $player $(sed -n $(echo $titlenumber)p < $HOME/.cache/ytview/channels/$channel/urls.txt | awk '{print $2}') > /dev/null 2>&1 &
@@ -150,6 +168,10 @@ searchview()
 
   #Let the user choose the video number
   read -p "Choose a video: " titlenumber
+  if [[ -n ${titlenumber//[0-9]/} ]]; then
+    echo "Canceled." >&2
+    exit 0
+  fi
 
   #Play the video with your favorite player
   $player $(sed -n $(echo $titlenumber)p < $HOME/.cache/ytview/searches/$search/urls.txt | awk '{print $2}') > /dev/null 2>&1 &
