Stylistic changes to geo

diff --git a/geo/geo b/geo/geo
--- a/geo/geo
+++ b/geo/geo
@@ -1,75 +1,72 @@
 #!/usr/bin/env bash
 
-#
 # Bash utility for getting specific network info
 # Author: Jake Meyer
 # Github: https://github.com/jakewmeyer
-#
 
 currentVersion="1.15.2"
 configuredClient=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-    if  command -v curl &>/dev/null ; then
+getConfiguredClient() {
+    if  command -v curl &>/dev/null; then
       configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
+    elif command -v wget &>/dev/null; then
       configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
+    elif command -v fetch &>/dev/null; then
       configuredClient="fetch"
     else
       echo "Error: This tool reqires either curl, wget, or fetch to be installed."
       return 1
     fi
-
 }
 
 ## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
+httpGet() {
   case "$configuredClient" in
-    curl) curl -A curl -s "$@";;
-    wget) wget -qO- "$@";;
-    fetch) fetch -o "...";;
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    fetch) fetch -o "..." ;;
   esac
 }
+
 # Parse arguments passed + help formatting
 usage() {
-    echo "Geo"
-    echo "Description: Provides quick access for wan, lan, router, dns, mac, and ip geolocation data"
-    echo "Usage: geo [flag]"
-    echo "  -w  Returns WAN IP"
-    echo "  -l  Returns LAN IP(s)"
-    echo "  -r  Returns Router IP"
-    echo "  -d  Returns DNS Nameserver"
-    echo "  -m  Returns MAC address for interface. Ex. eth0"
-    echo "  -g  Returns Current IP Geodata"
-    echo "Examples:"
-    echo "  geo -g"
-    echo "  geo -wlrdgm eth0"
-    echo "Custom Geo Output =>"
-    echo "[all] [query] [city] [region] [country] [zip] [isp]"
-    echo "Example: geo -a 8.8.8.8 -o city,zip,isp"
-    echo "  -o  [options] Returns Specific Geodata"
-    echo "  -a  [address] For specific ip in -s"
-    echo "  -v  Returns Version"
-    echo "  -h  Returns Help Screen"
-    echo "  -u  Updates Bash-Snippets"
+cat <<EOF
+Geo
+Description: Provides quick access for wan, lan, router, dns, mac, and ip geolocation data
+Usage: geo [flag]
+  -w  Returns WAN IP
+  -l  Returns LAN IP(s)
+  -r  Returns Router IP
+  -d  Returns DNS Nameserver
+  -m  Returns MAC address for interface. Ex. eth0
+  -g  Returns Current IP Geodata
+Examples:
+  geo -g
+  geo -wlrdgm eth0
+Custom Geo Output => [all] [query] [city] [region] [country] [zip] [isp]
+Example: geo -a 8.8.8.8 -o city,zip,isp
+  -o [options]  Returns Specific Geodata
+  -a [address]  For specific IP in -s
+  -v            Returns Version
+  -h            Returns Help Screen
+  -u            Updates Bash-Snippets
+EOF
     exit
 }
 
 # Displays version number
 version() {
-  echo "Version $currentVersion";
+  echo "Version $currentVersion"
 }
 
-# Fetches WAN ip address
+# Fetches WAN IP address
 wan_search() {
   httpGet https://api.ipify.org?format=json | grep -Eo "[0-9.]*"
 }
 
-# Fetches current LAN ip address
+# Fetches current LAN IP address
 lan_search() {
   if [ "$(uname)" = "Darwin" ]; then
     ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
@@ -131,9 +128,7 @@ specific_geo() {
   fi
 }
 
-
-update()
-{
+update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 1.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
@@ -142,10 +137,10 @@ update()
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]];then
+  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]];then
+  elif [[ $latestVersion == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
@@ -153,16 +148,16 @@ update()
       echo "Version $latestVersion available"
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
-      if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
-        cd  ~ || { echo 'Update Failed' ; exit 1 ; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName  ||  { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+      if [[ "$answer" == [Yy] ]] ;then
+        cd  ~ || { echo 'Update Failed'; exit 1; }
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
         git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version" ; exit 1; }
-        cd $repositoryName ||  { echo 'Update Failed' ; exit 1 ;}
+        cd $repositoryName || { echo 'Update Failed' ; exit 1 ;}
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName ||  { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
@@ -170,45 +165,38 @@ update()
       echo "$repositoryName is already the latest version"
     fi
   fi
-
 }
 
-
-
-checkInternet()
-{
+checkInternet() {
   httpGet google.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query google with a get request
 }
 
-
 # Option parsing "controller"
 optspec="uwlrdm:go:a:vh*:"
-while getopts "$optspec" optchar
-do
-    case "${optchar}" in
-        w) getConfiguredClient && checkInternet && wan_search || exit 1;;
-        l) lan_search ;;
-        r) router_search ;;
-        d) dns_search ;;
-        m) MAC=$OPTARG mac_search;;
-        g) getConfiguredClient && checkInternet && geodata_search || exit 1 ;;
-        a) ADDRESS=$OPTARG ;;
-        o) getConfiguredClient && checkInternet && OPTIONS=$OPTARG specific_geo || exit 1 ;;
-        v) version ;;
-        h) usage ;;
-        u) getConfiguredClient && checkInternet && update || exit 1 ;;
-        *) usage ;;
-    esac
+while getopts "$optspec" optchar; do
+  case "${optchar}" in
+    w) getConfiguredClient && checkInternet && wan_search || exit 1 ;;
+    l) lan_search ;;
+    r) router_search ;;
+    d) dns_search ;;
+    m) MAC=$OPTARG mac_search ;;
+    g) getConfiguredClient && checkInternet && geodata_search || exit 1 ;;
+    a) ADDRESS=$OPTARG ;;
+    o) getConfiguredClient && checkInternet && OPTIONS=$OPTARG specific_geo || exit 1 ;;
+    v) version ;;
+    h) usage ;;
+    u) getConfiguredClient && checkInternet && update || exit 1 ;;
+    *) usage ;;
+  esac
 done
 
 # Makes geo command default to help screen for usability
-if [ $# -eq 0 ];
-then
-    usage
-    exit 0
-elif [[ $1 == "update" ]];then
+if [ $# -eq 0 ]; then
+  usage
+  exit 0
+elif [[ $1 == "update" ]]; then
   getConfiguredClient && checkInternet && update || exit 1
-elif [[ $1 == "help" ]];then
+elif [[ $1 == "help" ]]; then
   usage
   exit 0
 fi
