Only check internet when neccessary, speeds up options that dont need it

diff --git a/currency/currency b/currency/currency
--- a/currency/currency
+++ b/currency/currency
@@ -227,7 +227,7 @@ EOF
 }
 
 getConfiguredClient || exit 1
-checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+
 
 while getopts "uvh" opt; do
   case "$opt" in
@@ -240,7 +240,8 @@ while getopts "uvh" opt; do
     v)  echo "Version $currentVersion"
         exit 0
         ;;
-    u)  update
+    u)  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+        update
         exit 0
         ;;
     :)  echo "Option -$OPTARG requires an argument." >&2
@@ -250,6 +251,7 @@ while getopts "uvh" opt; do
 done
 
 if [[ $# == 0 ]]; then
+  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
   getBase # get base currency
   getExchangeTo # get exchange to currency
   getAmount # get the amount to be converted
@@ -270,9 +272,12 @@ elif [[ $# == "2" ]]; then
   usage
   exit 1
 elif [[ $# == "3" ]]; then
+  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
   checkBase $1
   checkExchangeTo $2
   checkAmount $3
   convertCurrency
   exit 0
+else
+  echo "Error: too many arguments."
 fi
