Remove sparrow files, update formatting

diff --git a/cryptocurrency/cryptocurrency b/cryptocurrency/cryptocurrency
--- a/cryptocurrency/cryptocurrency
+++ b/cryptocurrency/cryptocurrency
@@ -3,17 +3,17 @@
 
 base=""
 exchangeTo=""
-currentVersion="1.14.2"
+currentVersion="1.15.2"
 configuredClient=""
 
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
-    if  command -v curl &>/dev/null ; then
+    if command -v curl &>/dev/null; then
       configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
+    elif command -v wget &>/dev/null; then
       configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
+    elif command -v fetch &>/dev/null; then
       configuredClient="fetch"
     else
       echo "Error: This tool reqires either curl, wget, or fetch to be installed."
@@ -26,9 +26,9 @@ getConfiguredClient()
 httpGet()
 {
   case "$configuredClient" in
-    curl) curl -A curl -s -N "$@";;
-    wget) wget -qO- "$@";;
-    fetch) fetch -o "...";;
+    curl) curl -A curl -s -N "$@" ;;
+    wget) wget -qO- "$@" ;;
+    fetch) fetch -o "..." ;;
   esac
 }
 
@@ -38,7 +38,7 @@ checkValidCurrency()
   if [[ $1 != "BTC" && $1 != "ETH" \
       && $1 != "XRP" && $1 != "LTC" && $1 != "XEM" \
       && $1 != "ETC" && $1 != "DASH" && $1 != "MIOTA" \
-      && $1 != "XMR" && $1 != "STRAT" ]];then
+      && $1 != "XMR" && $1 != "STRAT" ]]; then
     echo "1"
   else
     echo "0"
@@ -51,7 +51,7 @@ checkTargetCurrency()
       && $1 != "CAD" && $1 != "CHF" && $1 != "CNY" \
       && $1 != "EUR" && $1 != "GBP" && $1 != "HKD" \
       && $1 != "IDR" && $1 != "INR" && $1 != "JPY" && $1 != "KRW" \
-      && $1 != "MXN" && $1 != "RUB" && $1 != "USD" ]];then
+      && $1 != "MXN" && $1 != "RUB" && $1 != "USD" ]]; then
     echo "1"
   else
     echo "0"
@@ -65,19 +65,20 @@ getBase()
   echo -n "What is the base currency: "
   read -r base
   base=$(echo $base | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $base) == "1"  ]];then
+  if [[ $(checkValidCurrency $base) == "1"  ]]; then
     unset base
     echo "Invalid base currency"
     getBase
   fi
 }
+
 ## Checks base currency from the user and validates it with all the possible currency
 ## types available on the API (requires argument)
 checkBase()
 {
   base=$1
   base=$(echo $base | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $base) == "1" ]];then
+  if [[ $(checkValidCurrency $base) == "1" ]]; then
     unset base
     echo "Invalid base currency"
     exit 1
@@ -88,16 +89,16 @@ checkBase()
 transformBase()
 {
   case "$base" in 
-    "ETH") reqId="ethereum";;
-    "BTC") reqId="bitcoin";;
-    "XRP") reqId="ripple";;
-    "LTC") reqId="litecoin";;
-    "XEM") reqId="nem";;
-    "ETC") reqId="ethereum-classic";;
-    "DASH") reqId="dash";;
-    "MIOTA") reqId="iota";;
-    "XMR") reqId="monero";;
-    "STRAT") reqId="stratis";;
+    "ETH") reqId="ethereum" ;;
+    "BTC") reqId="bitcoin" ;;
+    "XRP") reqId="ripple" ;;
+    "LTC") reqId="litecoin" ;;
+    "XEM") reqId="nem" ;;
+    "ETC") reqId="ethereum-classic" ;;
+    "DASH") reqId="dash" ;;
+    "MIOTA") reqId="iota" ;;
+    "XMR") reqId="monero" ;;
+    "STRAT") reqId="stratis" ;;
   esac
 }
 
@@ -108,7 +109,7 @@ getExchangeTo()
   echo -n "What currency to exchange to: "
   read -r exchangeTo
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
-  if [[ $(checkTargetCurrency $exchangeTo) == "1" ]];then
+  if [[ $(checkTargetCurrency $exchangeTo) == "1" ]]; then
     echo "Invalid exchange currency"
     unset exchangeTo
     getExchangeTo
@@ -121,7 +122,7 @@ checkExchangeTo()
 {
   exchangeTo=$1
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
-  if [[ $(checkTargetCurrency $exchangeTo) == "1" ]];then
+  if [[ $(checkTargetCurrency $exchangeTo) == "1" ]]; then
     echo "Invalid exchange currency"
     unset exchangeTo
     exit 1
@@ -134,8 +135,7 @@ getAmount()
 {
   echo -n "What is the amount being exchanged: "
   read -r amount
-  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]
-  then
+  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
     echo "The amount has to be a number"
     unset amount
     getAmount
@@ -147,8 +147,7 @@ getAmount()
 checkAmount()
 {
   amount=$1
-  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]
-  then
+  if [[ ! "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
     echo "The amount has to be a number"
     unset amount
     exit 1
@@ -168,13 +167,15 @@ convertCurrency()
   exchangeAmount=$(echo "$exchangeRate * $amount" | bc  )
   exchangeTo=$(echo "$exchangeTo" | tr '[:lower:]' '[:upper:]')
   base=$(echo "$base" | tr '[:lower:]' '[:upper:]')
-  echo
-  echo "========================="
-  echo "| $base to $exchangeTo"  
-  echo "| Rate: $exchangeRate"
-  echo "| $base: $amount"
-  echo "| $exchangeTo: $exchangeAmount"
-  echo "========================="
+  
+  cat <<EOF
+=========================
+| $base to $exchangeTo  
+| Rate: $exchangeRate
+| $base: $amount
+| $exchangeTo: $exchangeAmount
+=========================
+EOF
 }
 
 update()
@@ -187,10 +188,10 @@ update()
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]];then
+  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]];then
+  elif [[ $latestVersion == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
@@ -198,16 +199,16 @@ update()
       echo "Version $latestVersion available"
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
-      if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
-        cd  ~ || { echo 'Update Failed' ; exit 1 ; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName  ||  { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
-        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version" ; exit 1; }
-        cd $repositoryName ||  { echo 'Update Failed' ; exit 1 ;}
+      if [[ "$answer" == [Yy] ]]; then
+        cd  ~ || { echo 'Update Failed'; exit 1; }
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version"; exit 1; }
+        cd $repositoryName || { echo 'Update Failed' ; exit 1 ;}
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName ||  { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
@@ -215,65 +216,62 @@ update()
       echo "$repositoryName is already the latest version"
     fi
   fi
-
 }
 
 usage()
 {
-  echo "CryptoCurrency"
-  echo -e "\n"
-  echo "Description: A realtime cryptocurrency converter."
-  echo "   With no flags it will guide you through the cryptocurrency exchange"
-  echo -e "\n"
-  echo "Usage: cryptocurrency or cryptocurrency [flag] or cryptocurrency [base] [exchangeTo] [amount]"
-  echo "  -u Update Bash-Snippet Tools"
-  echo "  -h Show the help"
-  echo "  -v Get the tool version"
-  echo -e "\n"
-  echo "Supported Base Currencies:"
-  echo " ___________________________"
-  echo "| BTC | ETH | XRP  | LTC   |"
-  echo "| XEM | ETC | DASH | MIOTA |"
-  echo "| XMR | STRAT              |"
-  echo " ___________________________"
-  echo -e "\n"
-  echo "Supported Target Currencies:"
-  echo " ________________________"
-  echo "| AUD | BRL | CAD | CHF |"
-  echo "| CNY | EUR | GBP | HKD |"
-  echo "| IDR | INR | JPY | KRW |"
-  echo "| MXN | RUB | USD       |"
-  echo " _______________________ "
-  echo "Examples:"
-  echo "  cryptocurrency BTC USD 12.35"
-  echo "  cryptocurrency"
+  cat <<EOF
+CryptoCurrency
+
+Description: A realtime cryptocurrency converter.
+With no flags it will guide you through the cryptocurrency exchange
+
+Usage: cryptocurrency or cryptocurrency [flag] or cryptocurrency [base] [exchangeTo] [amount]
+   -u Update Bash-Snippet Tools
+   -h Show the help
+   -v Get the tool version
+
+Supported Base Currencies:
+ ___________________________
+| BTC | ETH | XRP  | LTC   |
+| XEM | ETC | DASH | MIOTA |
+| XMR | STRAT              |
+ ___________________________
+
+Supported Target Currencies:
+ ________________________
+| AUD | BRL | CAD | CHF |
+| CNY | EUR | GBP | HKD |
+| IDR | INR | JPY | KRW |
+| MXN | RUB | USD       |
+ _______________________ 
+
+Examples:
+  cryptocurrency BTC USD 12.35
+  cryptocurrency
+EOF
 }
 
 getConfiguredClient || exit 1
 checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
 
 while getopts "uvh" opt; do
-  case $opt in
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-    ;;
-    h)
-      usage
-      exit 0
-    ;;
-    v)
-      echo "Version $currentVersion"
-      exit 0
-    ;;
-    u)
-      update
-      exit 0
-    ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-    ;;
+  case "$opt" in
+    \?) echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    h)  usage
+        exit 0
+        ;;
+    v)  echo "Version $currentVersion"
+        exit 0
+        ;;
+    u)  update
+        exit 0
+        ;;
+    :)  echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
   esac
 done
 
@@ -285,7 +283,7 @@ if [[ $# == 0 ]]; then
   convertCurrency # grab the exhange rate and perform the conversion
   exit 0
 elif [[ $# == "1" ]]; then
-  if [[ $1 == "update" ]];then
+  if [[ $1 == "update" ]]; then
     update
   elif [[ $1 == "help" ]]; then
     usage
@@ -298,7 +296,7 @@ elif [[ $# == "2" ]]; then
   echo "Not a valid argument"
   usage
   exit 1
-elif [[ $# == "3" ]];then
+elif [[ $# == "3" ]]; then
   checkBase $1
   checkExchangeTo $2
   checkAmount $3
