little stylistic changes

diff --git a/movies/movies b/movies/movies
--- a/movies/movies
+++ b/movies/movies
@@ -33,7 +33,7 @@ getConfiguredPython()
   fi
 }
 
-if [[ $(uname) != "Darwin" ]];then
+if [[ $(uname) != "Darwin" ]]; then
   python()
   {
     case "$configuredPython" in
@@ -47,9 +47,9 @@ fi
 httpGet()
 {
   case "$configuredClient" in
-    curl) curl -A curl -s "$@";;
-    wget) wget -qO- "$@";;
-    fetch) fetch -o "...";;
+    curl) curl -A curl -s "$@" ;;
+    wget) wget -qO- "$@" ;;
+    fetch) fetch -o "..." ;;
   esac
 }
 
@@ -68,7 +68,7 @@ getMovieInfo()
   export PYTHONIOENCODING=utf8 #necessary for python in some cases
   movieInfo=$(httpGet "http://www.omdbapi.com/?t=$movie&apikey=$apiKey") > /dev/null # query the server and get the JSON response
   checkResponse=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Response']" 2> /dev/null)
-  if [[ $checkResponse == "False" ]];then { echo "No movie found" ; return 1 ;} fi ## check to see if the movie was found
+  if [[ $checkResponse == "False" ]]; then { echo "No movie found" ; return 1 ;} fi ## check to see if the movie was found
   # The rest of the code is just extrapolating the data with python from the JSON response
   title=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Title']" 2> /dev/null)
   year=$(echo $movieInfo | python -c "import sys, json; print json.load(sys.stdin)['Year']" 2> /dev/null)
@@ -94,21 +94,25 @@ printMovieInfo()
   echo "| Title: $title"
   echo "| Year: $year"
   echo "| Runtime: $runtime"
-  if [[ $imdbScore != "" ]];then echo "| IMDB: $imdbScore"; fi
-  if [[ $tomatoScore != "" ]];then echo "| Tomato: $tomatoScore"; fi
+  if [[ $imdbScore != "" ]]; then echo "| IMDB: $imdbScore"; fi
+  if [[ $tomatoScore != "" ]]; then echo "| Tomato: $tomatoScore"; fi
   if $detail; then
-    if [[ $metacriticScore != "" ]]; then echo "| Metascore: $metacriticScore"; fi fi
+    if [[ $metacriticScore != "" ]]; then echo "| Metascore: $metacriticScore"; fi
+  fi
   if [[ $rated != "N/A" && $rated != "" ]]; then echo "| Rated: $rated"; fi
   echo "| Genre: $genre"
   echo "| Director: $director"
   echo "| Actors: $actors"
   if [[ $plot != "N/A" && $plot != "" ]]; then echo "| Plot: $plot"; fi
   if $detail; then
-    if [[ $boxOffice != "" ]]; then echo "| Box Office: $boxOffice"; fi fi
+    if [[ $boxOffice != "" ]]; then echo "| Box Office: $boxOffice"; fi
+  fi
   if $detail; then
-    if [[ $production != "" ]]; then echo "| Production: $production"; fi fi
+    if [[ $production != "" ]]; then echo "| Production: $production"; fi
+  fi
   if $detail; then
-    if [[ $awards != "" ]]; then echo "| Awards: $awards"; fi fi
+    if [[ $awards != "" ]]; then echo "| Awards: $awards"; fi
+  fi
   echo '=================================================='
   echo
 }
@@ -123,7 +127,7 @@ update()
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]];then
+  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
   elif [[ $latestVersion == "" ]];then
@@ -134,16 +138,16 @@ update()
       echo "Version $latestVersion available"
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
-      if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
-        cd  ~ || { echo 'Update Failed' ; exit 1 ; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName  ||  { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+      if [[ "$answer" == [Yy] ]]; then
+        cd  ~ || { echo 'Update Failed' ; exit 1; }
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
         git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version" ; exit 1; }
-        cd $repositoryName ||  { echo 'Update Failed' ; exit 1 ;}
+        cd $repositoryName ||  { echo 'Update Failed' ; exit 1; }
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName ||  { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
@@ -156,19 +160,21 @@ update()
 
 usage()
 {
-  echo "Movies"
-  echo "Description: Provides relevant information about a certain movie."
-  echo "Usage: movies [flag] or movies [movieToSearch]"
-  echo "  -u Update Bash-Snippet Tools"
-  echo "  -h Show the help"
-  echo "  -v Get the tool version"
-  echo "  -d Show detailed information"
-  echo "Examples:"
-  echo "  movies Argo"
-  echo "  movies Inception"
+  cat <<EOF
+Movies
+Description: Provides relevant information about a certain movie.
+Usage: movies [flag] or movies [movieToSearch]
+  -u  Update Bash-Snippet Tools
+  -h  Show the help
+  -v  Get the tool version
+  -d  Show detailed information
+Examples:
+  movies Argo
+  movies Inception
+EOF
 }
 
-if [[ $(uname) != "Darwin" ]];then getConfiguredPython || exit 1;fi
+if [[ $(uname) != "Darwin" ]]; then getConfiguredPython || exit 1; fi
 getConfiguredClient || exit 1
 checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
 
@@ -182,16 +188,16 @@ while getopts 'ud:hv' flag; do
     v) echo "Version $currentVersion"
        exit 0 ;;
     :) echo "Option -$OPTARG requires an argument." >&2
-     exit 1 ;;
+       exit 1 ;;
     *) exit 1 ;;
   esac
 done
 
 if [[ $# == 0 ]]; then
   usage
-elif [[ $1 == "update" ]];then
+elif [[ $1 == "update" ]]; then
   update
-elif [[ $1 == "help" ]];then
+elif [[ $1 == "help" ]]; then
   usage
 else
   getMovieInfo "$@" || exit 1 ## exit if we return 1 (chances are movie was not found)
