Adding support for httpie :smile:

diff --git a/cheat/cheat b/cheat/cheat
--- a/cheat/cheat
+++ b/cheat/cheat
@@ -16,10 +16,12 @@ getConfiguredClient()
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, or fetch to be installed."
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -30,6 +32,7 @@ httpGet()
   case "$configuredClient" in
     curl)  curl -A curl -s "$@" ;;
     wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
     fetch) fetch -o "..." ;;
   esac
 }
diff --git a/cryptocurrency/cryptocurrency b/cryptocurrency/cryptocurrency
--- a/cryptocurrency/cryptocurrency
+++ b/cryptocurrency/cryptocurrency
@@ -9,25 +9,27 @@ configuredClient=""
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
-    if command -v curl &>/dev/null; then
-      configuredClient="curl"
-    elif command -v wget &>/dev/null; then
-      configuredClient="wget"
-    elif command -v fetch &>/dev/null; then
-      configuredClient="fetch"
-    else
-      echo "Error: This tool reqires either curl, wget, or fetch to be installed."
-      return 1
-    fi
-
+  if  command -v curl &>/dev/null; then
+    configuredClient="curl"
+  elif command -v wget &>/dev/null; then
+    configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
+  else
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    return 1
+  fi
 }
 
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
   case "$configuredClient" in
-    curl) curl -A curl -s -N "$@" ;;
-    wget) wget -qO- "$@" ;;
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
     fetch) fetch -o "..." ;;
   esac
 }
@@ -55,7 +57,7 @@ checkTargetCurrency()
     echo "1"
   else
     echo "0"
-  fi  
+  fi
 }
 
 ## Grabs the base currency from the user and validates it with all the possible currency
@@ -88,7 +90,7 @@ checkBase()
 # Matches the symbol to the appropriate ids regarding the API calling.
 transformBase()
 {
-  case "$base" in 
+  case "$base" in
     "ETH") reqId="ethereum" ;;
     "BTC") reqId="bitcoin" ;;
     "XRP") reqId="ripple" ;;
@@ -167,10 +169,10 @@ convertCurrency()
   exchangeAmount=$(echo "$exchangeRate * $amount" | bc  )
   exchangeTo=$(echo "$exchangeTo" | tr '[:lower:]' '[:upper:]')
   base=$(echo "$base" | tr '[:lower:]' '[:upper:]')
-  
+
   cat <<EOF
 =========================
-| $base to $exchangeTo  
+| $base to $exchangeTo
 | Rate: $exchangeRate
 | $base: $amount
 | $exchangeTo: $exchangeAmount
@@ -244,7 +246,7 @@ Supported Target Currencies:
 | CNY | EUR | GBP | HKD |
 | IDR | INR | JPY | KRW |
 | MXN | RUB | USD       |
- _______________________ 
+ _______________________
 
 Examples:
   cryptocurrency BTC USD 12.35
diff --git a/movies/movies b/movies/movies
--- a/movies/movies
+++ b/movies/movies
@@ -9,16 +9,29 @@ detail=false
 ## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
-    if  command -v curl &>/dev/null ; then
-      configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
-      configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
-      configuredClient="fetch"
-    else
-      echo "Error: This tool reqires either curl, wget, or fetch to be installed."
-      return 1
-    fi
+  if  command -v curl &>/dev/null; then
+    configuredClient="curl"
+  elif command -v wget &>/dev/null; then
+    configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
+  else
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    return 1
+  fi
+}
+
+## Allows to call the users configured client without if statements everywhere
+httpGet()
+{
+  case "$configuredClient" in
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
+    fetch) fetch -o "..." ;;
+  esac
 }
 
 getConfiguredPython()
@@ -42,17 +55,6 @@ if [[ $(uname) != "Darwin" ]]; then
     esac
   }
 fi
-
-## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
-  case "$configuredClient" in
-    curl) curl -A curl -s "$@" ;;
-    wget) wget -qO- "$@" ;;
-    fetch) fetch -o "..." ;;
-  esac
-}
-
 
 checkInternet()
 {
diff --git a/newton/newton b/newton/newton
--- a/newton/newton
+++ b/newton/newton
@@ -6,12 +6,30 @@ configuredClient=""
 flagCount="0"
 declare -a simpleOperations=(simplify factor derive integrate zeroes roots tangent area cos sin tan arccos arcsin arctan abs log)
 
+## This function determines which http get tool the system has installed and returns an error if there isnt one
+getConfiguredClient()
+{
+  if  command -v curl &>/dev/null; then
+    configuredClient="curl"
+  elif command -v wget &>/dev/null; then
+    configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
+  else
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    return 1
+  fi
+}
+
 ## Allows to call the users configured client without if statements everywhere
 httpGet()
 {
   case "$configuredClient" in
-    curl) curl -A curl -s "$@" ;;
-    wget) wget -qO- "$@" ;;
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
     fetch) fetch -o "..." ;;
   esac
 }
@@ -61,21 +79,6 @@ update()
       echo "$repositoryName is already the latest version"
     fi
   fi
-}
-
-## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-    if  command -v curl &>/dev/null ; then
-      configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
-      configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
-      configuredClient="fetch"
-    else
-      echo "Error: This tool reqires either curl, wget, or fetch to be installed."
-      return 1
-    fi
 }
 
 validateExpression()
diff --git a/qrify/qrify b/qrify/qrify
--- a/qrify/qrify
+++ b/qrify/qrify
@@ -5,16 +5,32 @@ currentVersion="1.16.2"
 multiline="0" # flag that indicates multiline option
 
 
+## This function determines which http get tool the system has installed and returns an error if there isnt one
 getConfiguredClient()
 {
-  if command -v curl &> /dev/null; then
+  if  command -v curl &>/dev/null; then
     configuredClient="curl"
-  elif command -v wget &> /dev/null; then
+  elif command -v wget &>/dev/null; then
     configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
+  elif command -v fetch &>/dev/null; then
+    configuredClient="fetch"
   else
-    echo "Error: This tool requires either curl or wget to be installed." >&2
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
+}
+
+## Allows to call the users configured client without if statements everywhere
+httpGet()
+{
+  case "$configuredClient" in
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
+    fetch) fetch -o "..." ;;
+  esac
 }
 
 update()
@@ -55,14 +71,6 @@ update()
       echo "${repositoryName} is already the latest version"
     fi
   fi
-}
-
-httpGet()
-{
-  case "${configuredClient}" in
-    curl) curl -A curl -s "$@";;
-    wget) wget -qO- "$@";;
-  esac
 }
 
 makeqr()
diff --git a/short/short b/short/short
--- a/short/short
+++ b/short/short
@@ -12,12 +12,25 @@ getConfiguredClient()
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, or fetch to be installed."
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
+}
+
+## Allows to call the users configured client without if statements everywhere
+httpGet()
+{
+  case "$configuredClient" in
+    curl)  curl -A curl -s "$@" ;;
+    wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
+    fetch) fetch -o "..." ;;
+  esac
 }
 
 
@@ -43,15 +56,6 @@ if [[ $(uname) != "Darwin" ]];then
   }
 fi
 
-## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
-  case "$configuredClient" in
-    curl)  curl -A curl -s "$@" ;;
-    wget)  wget -qO- "$@" ;;
-    fetch) fetch -o "..." ;;
-  esac
-}
 
 checkInternet()
 {
diff --git a/todo/todo b/todo/todo
--- a/todo/todo
+++ b/todo/todo
@@ -11,10 +11,12 @@ getConfiguredClient()
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, or fetch to be installed."
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -25,6 +27,7 @@ httpGet()
   case "$configuredClient" in
     curl)  curl -A curl -s "$@" ;;
     wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
     fetch) fetch -o "..." ;;
   esac
 }
@@ -164,7 +167,7 @@ while getopts "cr:a:guvh" opt; do
         ;;
     c)  if [[ $flag == "" ]]; then
           flag="clear"
-        else  
+        else
           echo "Error: all flags are mutually exclusive"
           exit 1
         fi
diff --git a/ytview/ytview b/ytview/ytview
--- a/ytview/ytview
+++ b/ytview/ytview
@@ -16,17 +16,14 @@ getConfiguredClient()
     configuredClient="curl"
   elif command -v wget &>/dev/null; then
     configuredClient="wget"
+  elif command -v http &>/dev/null; then
+    configuredClient="httpie"
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, or fetch to be installed." >&2
+    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed\." >&2
     return 1
   fi
-}
-
-checkInternet()
-{
-  httpGet google.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query google with a get request
 }
 
 ## Allows to call the users configured client without if statements everywhere
@@ -35,8 +32,14 @@ httpGet()
   case "$configuredClient" in
     curl)  curl -A curl -s "$@" ;;
     wget)  wget -qO- "$@" ;;
+    httpie) http -b GET "$@" ;;
     fetch) fetch -o "..." ;;
   esac
+}
+
+checkInternet()
+{
+  httpGet google.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query google with a get request
 }
 
 update()
